from . import auto_checkout
from . import product_customer_reference
from . import product_template
from . import sale_order
from . import account_move
from . import maintenance_checklist_template
from . import maintenance_equipment
from . import maintenance_request
from . import maintenance_plan
from . import maintenance_material_line
from . import maintenance_material_template
from . import maintenance_equipment_history_wizard